import { Injectable } from '@angular/core';
import { InMemoryDbService } from 'angular-in-memory-web-api';
import { Hero } from './hero';
import { Comment } from './comment';

@Injectable({
  providedIn: 'root',
})
export class InMemoryDataService implements InMemoryDbService {
  createDb() {
    const heroes = [
      { id: 1, name: 'James Howlett', alias:'Wolverine', picture: 'wolverine.png', powers:["Sharp Adamantium claws", "Regeneration"], description: "Cursed with a berserker fury, the violent mutant known as Wolverine has a reputation of both as an outstanding super hero and as a lethal killer. Born as James Howlett to a wealthy Canadian family at the end of the 19th century, he was forced to abandon his family after the tragic manifestation of his bestial abilities of accelerated healing factor, keenly enhanced senses and bone claws in each hand. Adopting the name Logan, he wandered the world, living a long life filled with blood, war and betrayal, having vile Sabretooth as his archenemy, and the Japanese warrior Ogun as his sensei. Unfortunately, by acting as a lone wolf, Logan was an unwitting subject of the Weapon X Program and had his bones coated in indestructible Adamantium, becoming an even more lethal asset. Rescued and assisted by Mac and Heather Hudson, he joined Department H as a Canadian government operative known as the Wolverine."},
      { id: 2, name: 'Anthony Stark', alias: 'Iron Man', picture:'ironman.png', powers:[], description:"Tony Stark is a genius inventor and billionaire industrialist, who suits up in his armor of cutting-edge technology to become the super hero Iron Man. The adopted son of weapons manufacturer Howard Stark, Tony inherited his family's company at a young age following his parents' death. While overseeing a manufacturing plant in a foreign country, Stark was kidnapped by local terrorists. Instead of giving in to his captors' demands to build weapons for them, Stark created a powerful suit of armor for himself to escape. Returning to America, Stark further upgraded the armor and put his vast resources and intellect to use for the betterment of the world as Iron Man." },
      { id: 3, name: 'Bruce Banner', alias: 'Hulk', picture:'hulk.png', powers:[], description:"Dr. Bruce Banner, Ph.D. a.k.a. the Hulk is an American theoretical physicist, famed for his work into the studies of nuclear physics and gamma radiation. He was recruited by General Thaddeus 'Thunderbolt' Ross and the US Army to develop the first Gamma Bomb. During its first live test he was bombarded with a massive dose of gamma rays while saving Rick Jones, a kid who was out on the test site. He was mutated into a green behemoth, the living personification of rage, fueled by pure physical strength and would come to be known as the near mindless 'Incredible Hulk'. Fearful of the damage that Hulk could inflict, as well as fleeing from the military, he went on the run. He later found a home among the Avengers, 'Earth's Mightiest Heroes', for a short time." },
      { id: 4, name: 'Peter Parker', alias: 'Spiderman', picture:'spiderman.png', powers:[], description:"Sometimes student, sometimes scientist and sometimes photographer, Peter Parker is a full-time super hero better known as the web-slinging and wall-crawling Spider-Man. As an orphaned child, Peter was raised by his Uncle Ben and Aunt May. At a science expo, Peter was bitten by an errant radioactive spider which granted him an array of arachnid powers. He initially became Spider-Man to use his powers as an entertainer, growing so conceited he didn't bother stopping a passerby burglar. In a twist of fate, the same burglar wound up killing Peter's Uncle Ben, leading him to realize that he needed to use his powers responsibly. From then on, Spider-Man became a crime-fighting vigilante."},
      { id: 5, name: 'Steve Rogers', alias: 'Captain America', picture:'captain.png', powers:[], description:'Cpt. Steven "Steve" Rogers a.k.a. Captain America, the First Avenger, was rejected by the U.S. Army during World War II due to numerous health problems. He ultimately volunteered for Project Rebirth where he received the Super-Soldier Serum developed by Dr. Abraham Erskine. The serum greatly enhanced his frail body to the peak of human physicality. As the Sentinel of Liberty, alongside his best friend Bucky Barnes and the Invaders, Rogers and others helped the allies win the war, but not before he was lost at sea and frozen in ice in a form of suspended animation for decades. He was thawed out in the modern age to continue the battle alongside his new allies the Avengers. Cap is loyal to no politician or government and instead upholds the "timeless principles of freedom, equality and justice of the American Dream".' },
      { id: 6, name: 'Thor Odinson', alias: 'Thor', picture:'thor.png', powers:[], description:"Thor is the God of Thunder, a member of the race known as the Asgardians, a group of humanoid beings from the pocket dimension of Asgard, the Realm Eternal. Thor is the son of Odin, the All-Father and King of Asgard. He was worshiped by the humans known as Vikings and became part of Norse mythology. Armed with his enchanted Uru hammer Mjolnir, which helps him to channel his godly energies, he became the mightiest warrior in the Ten Realms. When his irresponsible and impetuous behavior became too much, Odin sent him to Midgard (more commonly known as Earth) as a disabled mortal medical student named Donald Blake, stripped of his memory. After learning humility, he regained his memory as well as his godly powers. Thor went on to become a champion for Midgard as well as one of the founding members of the Avengers, 'Earth's Mightiest Heroes'." },
      { id: 7, name: "T'Challa", alias: 'Black Panther', picture:'blackpanther.png', powers:[], description:"T'Challa a.k.a. the Black Panther is the head of state of the African nation of Wakanda, the most technologically advanced country on Earth. In this role, he was the King/Chieftain, religious leader, and commander-in-chief all rolled into one. He is also considered among the top intellects in the world. Using Wakanda's advanced Vibranium technology and his own abilities and fortune, he pledged his life to the service of all humankind. He would go on to become a prominent member of the Avengers, and eventually become leader of the team." },
      { id: 8, name: 'Wanda Maximoff', alias: 'Scarlet Witch', picture:'scarlet.png', powers:[], description:"Wanda Maximoff, the Scarlet Witch, is a Romani sorceress and twin sister of the speedster Quicksilver. Once believed to have been mutant children of Magneto, the twins are in truth orphans enhanced by the High Evolutionary at Mount Wundagore in Transia. The Scarlet Witch became a conduit of chaos magic, allowing her to shift probabilities and warp reality itself by casting 'hexes'. After being saved from an angry mob by Magneto, the Scarlet Witch and her brother joined the Brotherhood of Evil Mutants to fight for Magneto's mutant supremacy cause. Disagreeing with Magneto's ruthless approach, the twins left him and joined the super-heroic Avengers instead." },
      { id: 9, name: 'Scott Lang', alias: 'Ant-Man', picture:'antman.png', powers:[], description:"Created by Stan Lee, Larry Lieber and Jack Kirby, Ant-Man's first appearance was in Tales to Astonish #27 (January 1962) but first appeared in costume in Tales to Astonish #35 (September 1962). The persona was originally the brilliant scientist Hank Pym's superhero alias after inventing a substance that can change size, but reformed thieves Scott Lang and Eric O'Grady also took on the mantle after the original changed his superhero identity to various other aliases, such as Giant-Man, Goliath, and Yellowjacket. Pym's Ant-Man is also a founding member of the super hero team known as the Avengers. The character has appeared in several films based on the Marvel character, such as Ant-Man (2015), Captain America: Civil War (2016), Ant-Man and the Wasp (2018), Avengers: Endgame (2019), and Ant-Man and the Wasp: Quantumania (2023)." },
      { id: 10, name: 'Wade Wilson', alias: 'Deadpool', picture:'deadpool.png', powers:[], description:'Deadpool is a character appearing in American comic books published by Marvel Comics. Created by Fabian Nicieza and Rob Liefeld, the character first appeared in New Mutants #98 (December 1990). In his comic book appearances, Deadpool is initially depicted as a supervillain of the New Mutants and X-Force, though later stories would portray him as an antihero. Deadpool is the alter ego of Wade Wilson, a disfigured Canadian mercenary with superhuman regenerative healing abilities. He is known for his tendency to joke incessantly and break the fourth wall for humorous effect.' }
  ];
  const comments = [
    { id: 1, username: 'user01', dateTime:'02/04/2023 08:35:29', heroId: 1, comment:"Test", replies: [], upVotes: 0, downVotes:0},
];
    return {heroes, comments};
  }

  genId(elements: Hero[]|Comment[]): number {
    return elements.length > 0 ? Math.max(...elements.map(e => e.id)) + 1 : 10;
  }
}